config/routes.rb
Rails.application.routes.draw do
  resources :add_userid_to_comments
  resources :add_userid_to_posts
  resources :users
  resources :comments
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/add_userid_to_comment.rb
class AddUseridToComment < ApplicationRecord
  belongs_to :user
end

app/controllers/add_userid_to_comments_controller.rb
class AddUseridToCommentsController < ApplicationController
  before_action :set_add_userid_to_comment, only: [:show, :edit, :update, :destroy]

  # GET /add_userid_to_comments
  # GET /add_userid_to_comments.json
  def index
    @add_userid_to_comments = AddUseridToComment.all
  end

  # GET /add_userid_to_comments/1
  # GET /add_userid_to_comments/1.json
  def show
  end

  # GET /add_userid_to_comments/new
  def new
    @add_userid_to_comment = AddUseridToComment.new
  end

  # GET /add_userid_to_comments/1/edit
  def edit
  end

  # POST /add_userid_to_comments
  # POST /add_userid_to_comments.json
  def create
    @add_userid_to_comment = AddUseridToComment.new(add_userid_to_comment_params)

    respond_to do |format|
      if @add_userid_to_comment.save
        format.html { redirect_to @add_userid_to_comment, notice: 'Add userid to comment was successfully created.' }
        format.json { render :show, status: :created, location: @add_userid_to_comment }
      else
        format.html { render :new }
        format.json { render json: @add_userid_to_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /add_userid_to_comments/1
  # PATCH/PUT /add_userid_to_comments/1.json
  def update
    respond_to do |format|
      if @add_userid_to_comment.update(add_userid_to_comment_params)
        format.html { redirect_to @add_userid_to_comment, notice: 'Add userid to comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @add_userid_to_comment }
      else
        format.html { render :edit }
        format.json { render json: @add_userid_to_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /add_userid_to_comments/1
  # DELETE /add_userid_to_comments/1.json
  def destroy
    @add_userid_to_comment.destroy
    respond_to do |format|
      format.html { redirect_to add_userid_to_comments_url, notice: 'Add userid to comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_add_userid_to_comment
      @add_userid_to_comment = AddUseridToComment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def add_userid_to_comment_params
      params.require(:add_userid_to_comment).permit(:user_id)
    end
end

app/helpers/add_userid_to_comments_helper.rb
module AddUseridToCommentsHelper
end

app/views/add_userid_to_comments/_form.html.erb
<%= form_with(model: add_userid_to_comment) do |form| %>
  <% if add_userid_to_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(add_userid_to_comment.errors.count, "error") %> prohibited this add_userid_to_comment from being saved:</h2>

      <ul>
        <% add_userid_to_comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/add_userid_to_comments/edit.html.erb
<h1>Editing Add Userid To Comment</h1>

<%= render 'form', add_userid_to_comment: @add_userid_to_comment %>

<%= link_to 'Show', @add_userid_to_comment %> |
<%= link_to 'Back', add_userid_to_comments_path %>

app/views/add_userid_to_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Add Userid To Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @add_userid_to_comments.each do |add_userid_to_comment| %>
      <tr>
        <td><%= add_userid_to_comment.user_id %></td>
        <td><%= link_to 'Show', add_userid_to_comment %></td>
        <td><%= link_to 'Edit', edit_add_userid_to_comment_path(add_userid_to_comment) %></td>
        <td><%= link_to 'Destroy', add_userid_to_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Add Userid To Comment', new_add_userid_to_comment_path %>

app/views/add_userid_to_comments/new.html.erb
<h1>New Add Userid To Comment</h1>

<%= render 'form', add_userid_to_comment: @add_userid_to_comment %>

<%= link_to 'Back', add_userid_to_comments_path %>

app/views/add_userid_to_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @add_userid_to_comment.user_id %>
</p>

<%= link_to 'Edit', edit_add_userid_to_comment_path(@add_userid_to_comment) %> |
<%= link_to 'Back', add_userid_to_comments_path %>